name: Build & Publish
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v1.0.0

    - name: Set up Node.js
      uses: actions/setup-node@v1.2.0
      with:
        node-version: '10.x'
    
    - name: Install dependencies
      run: npm install

    - name: Compile build
      run: npm run build

    - name: Commit changes
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: Federico Grandi
        author_email: fgrandi30@gmail.com
        message: "[auto] Update dist"
        path: dist
        pattern: "*.*"
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1.0.0
      with:
        ref: master

    - name: Check version changes
      uses: EndBug/version-check@v1.0.0
      id: check

    - name: Version update detected
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'

    - name: Set up Node.js for NPM
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: npm install

    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up Node.js for GPR
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1.2.0
      with:
        registry-url: 'https://npm.pkg.github.com'

    - name: Publish package to GPR
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      